# python
# This file is generated by a program (mib2py). 

import CISCO_QUEUE_MIB

OIDMAP = {
'1.3.6.1.4.1.9.9.37': CISCO_QUEUE_MIB.ciscoQueueMIB,
'1.3.6.1.4.1.9.9.37.1': CISCO_QUEUE_MIB.ciscoQueueObjects,
'1.3.6.1.4.1.9.9.37.2': CISCO_QUEUE_MIB.ciscoQueueTraps,
'1.3.6.1.4.1.9.9.37.3': CISCO_QUEUE_MIB.ciscoQueueConformance,
'1.3.6.1.4.1.9.9.37.3.1': CISCO_QUEUE_MIB.cQCompliances,
'1.3.6.1.4.1.9.9.37.3.2': CISCO_QUEUE_MIB.cQGroups,
'1.3.6.1.4.1.9.9.37.1.1.1.1': CISCO_QUEUE_MIB.cQIfQType,
'1.3.6.1.4.1.9.9.37.1.1.1.2': CISCO_QUEUE_MIB.cQIfTxLimit,
'1.3.6.1.4.1.9.9.37.1.1.1.3': CISCO_QUEUE_MIB.cQIfSubqueues,
'1.3.6.1.4.1.9.9.37.1.2.1.1': CISCO_QUEUE_MIB.cQStatsQNumber,
'1.3.6.1.4.1.9.9.37.1.2.1.2': CISCO_QUEUE_MIB.cQStatsDepth,
'1.3.6.1.4.1.9.9.37.1.2.1.3': CISCO_QUEUE_MIB.cQStatsMaxDepth,
'1.3.6.1.4.1.9.9.37.1.2.1.4': CISCO_QUEUE_MIB.cQStatsDiscards,
'1.3.6.1.4.1.9.9.37.1.3.1.1': CISCO_QUEUE_MIB.cQRotationOctets,
'1.3.6.1.4.1.9.9.37.3.2.1': CISCO_QUEUE_MIB.cQIfGroup,
'1.3.6.1.4.1.9.9.37.3.2.2': CISCO_QUEUE_MIB.cQStatsGroup,
'1.3.6.1.4.1.9.9.37.3.2.3': CISCO_QUEUE_MIB.cQRotationGroup,
}
