# python
# This file is generated by a program (mib2py). Any edits will be lost.

from pycopia.aid import Enum
import pycopia.SMI.Basetypes
Range = pycopia.SMI.Basetypes.Range
Ranges = pycopia.SMI.Basetypes.Ranges

from pycopia.SMI.Objects import ColumnObject, MacroObject, NotificationObject, RowObject, ScalarObject, NodeObject, ModuleObject, GroupObject

# imports 
from SNMPv2_SMI import MODULE_IDENTITY, NOTIFICATION_TYPE, OBJECT_TYPE, Integer32, Counter32
from SNMPv2_CONF import MODULE_COMPLIANCE, OBJECT_GROUP
from CISCO_SMI import ciscoMgmt
from SNMPv2_TC import TEXTUAL_CONVENTION, DisplayString, TimeStamp, TruthValue

class CISCO_SYSLOG_MIB(ModuleObject):
	path = '/usr/share/snmp/mibs/site/CISCO-SYSLOG-MIB'
	conformance = 3
	name = 'CISCO-SYSLOG-MIB'
	language = 2
	description = 'The MIB module to describe and store the system messages\ngenerated by the IOS.'

# nodes
class ciscoSyslogMIB(NodeObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41])
	name = 'ciscoSyslogMIB'

class ciscoSyslogMIBObjects(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1])
	name = 'ciscoSyslogMIBObjects'

class clogBasic(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1])
	name = 'clogBasic'

class clogHistory(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2])
	name = 'clogHistory'

class ciscoSyslogMIBNotificationPrefix(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 2])
	name = 'ciscoSyslogMIBNotificationPrefix'

class ciscoSyslogMIBNotifications(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 2, 0])
	name = 'ciscoSyslogMIBNotifications'

class ciscoSyslogMIBConformance(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 3])
	name = 'ciscoSyslogMIBConformance'

class ciscoSyslogMIBCompliances(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 3, 1])
	name = 'ciscoSyslogMIBCompliances'

class ciscoSyslogMIBGroups(NodeObject):
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 3, 2])
	name = 'ciscoSyslogMIBGroups'


# macros
# types 

class SyslogSeverity(pycopia.SMI.Basetypes.Enumeration):
	status = 1
	enumerations = [Enum(1, 'emergency'), Enum(2, 'alert'), Enum(3, 'critical'), Enum(4, 'error'), Enum(5, 'warning'), Enum(6, 'notice'), Enum(7, 'info'), Enum(8, 'debug')]

# scalars 
class clogNotificationsSent(ScalarObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1, 1])
	syntaxobject = pycopia.SMI.Basetypes.Counter32
	access = 4
	units = 'notifications'


class clogNotificationsEnabled(ScalarObject):
	access = 5
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1, 2])
	syntaxobject = pycopia.SMI.Basetypes.TruthValue


class clogMaxSeverity(ScalarObject):
	access = 5
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1, 3])
	syntaxobject = SyslogSeverity


class clogMsgIgnores(ScalarObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1, 4])
	syntaxobject = pycopia.SMI.Basetypes.Counter32
	access = 4
	units = 'messages'


class clogMsgDrops(ScalarObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 1, 5])
	syntaxobject = pycopia.SMI.Basetypes.Counter32
	access = 4
	units = 'messages'


class clogHistTableMaxLength(ScalarObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 1])
	syntaxobject = pycopia.SMI.Basetypes.Integer32
	access = 5
	units = 'entries'


class clogHistMsgsFlushed(ScalarObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 2])
	syntaxobject = pycopia.SMI.Basetypes.Counter32
	access = 4
	units = 'messages'


# columns
class clogHistIndex(ColumnObject):
	access = 2
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 1])
	syntaxobject = pycopia.SMI.Basetypes.Integer32


class clogHistFacility(ColumnObject):
	access = 4
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 2])
	syntaxobject = pycopia.SMI.Basetypes.DisplayString


class clogHistSeverity(ColumnObject):
	access = 4
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 3])
	syntaxobject = SyslogSeverity


class clogHistMsgName(ColumnObject):
	access = 4
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 4])
	syntaxobject = pycopia.SMI.Basetypes.DisplayString


class clogHistMsgText(ColumnObject):
	access = 4
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 5])
	syntaxobject = pycopia.SMI.Basetypes.DisplayString


class clogHistTimestamp(ColumnObject):
	access = 4
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1, 6])
	syntaxobject = pycopia.SMI.Basetypes.TimeStamp


# rows 
class clogHistoryEntry(RowObject):
	status = 1
	index = pycopia.SMI.Objects.IndexObjects([clogHistIndex], False)
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 1, 2, 3, 1])
	access = 2
	columns = {'clogHistIndex': clogHistIndex, 'clogHistFacility': clogHistFacility, 'clogHistSeverity': clogHistSeverity, 'clogHistMsgName': clogHistMsgName, 'clogHistMsgText': clogHistMsgText, 'clogHistTimestamp': clogHistTimestamp}


# notifications (traps) 
class clogMessageGenerated(NotificationObject):
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 2, 0, 1])

# groups 
class ciscoSyslogMIBGroup(GroupObject):
	access = 2
	status = 1
	OID = pycopia.SMI.Basetypes.ObjectIdentifier([1, 3, 6, 1, 4, 1, 9, 9, 41, 3, 2, 1])
	group = [clogNotificationsSent, clogNotificationsEnabled, clogMaxSeverity, clogMsgIgnores, clogMsgDrops, clogHistTableMaxLength, clogHistMsgsFlushed, clogHistFacility, clogHistSeverity, clogHistMsgName, clogHistMsgText, clogHistTimestamp]

# capabilities 

# special additions

# Add to master OIDMAP.
from pycopia import SMI
SMI.update_oidmap(__name__)
