# python
# This file is generated by a program (mib2py). 

import CISCO_DS0BUNDLE_EXT_MIB

OIDMAP = {
'1.3.6.1.4.1.9.10.33': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtMIB,
'1.3.6.1.4.1.9.10.33.1': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtMIBObjects,
'1.3.6.1.4.1.9.10.33.1.1': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleConfig,
'1.3.6.1.4.1.9.10.33.1.2': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleInfo,
'1.3.6.1.4.1.9.10.33.3': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtMIBConformance,
'1.3.6.1.4.1.9.10.33.3.1': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtMIBCompliances,
'1.3.6.1.4.1.9.10.33.3.2': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtMIBGroups,
'1.3.6.1.4.1.9.10.33.1.1.1.1.1': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleExtDs1Index,
'1.3.6.1.4.1.9.10.33.1.1.1.1.2': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleExtChannelMap,
'1.3.6.1.4.1.9.10.33.1.1.1.1.3': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleExtEncapType,
'1.3.6.1.4.1.9.10.33.1.1.1.1.4': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleExtChannelRate,
'1.3.6.1.4.1.9.10.33.1.2.1.1.1': CISCO_DS0BUNDLE_EXT_MIB.cdsx0BundleUseDs0Used,
'1.3.6.1.4.1.9.10.33.3.2.1': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtConfigGroup,
'1.3.6.1.4.1.9.10.33.3.2.2': CISCO_DS0BUNDLE_EXT_MIB.ciscoDs0BundleExtInfoGroup,
}
