# python
# This file is generated by a program (mib2py). 

import IF_INVERTED_STACK_MIB

OIDMAP = {
'1.3.6.1.2.1.77': IF_INVERTED_STACK_MIB.ifInvertedStackMIB,
'1.3.6.1.2.1.77.1': IF_INVERTED_STACK_MIB.ifInvMIBObjects,
'1.3.6.1.2.1.77.1.2': IF_INVERTED_STACK_MIB.ifInvConformance,
'1.3.6.1.2.1.77.1.2.1': IF_INVERTED_STACK_MIB.ifInvGroups,
'1.3.6.1.2.1.77.1.2.2': IF_INVERTED_STACK_MIB.ifInvCompliances,
'1.3.6.1.2.1.77.1.1.1.1': IF_INVERTED_STACK_MIB.ifInvStackStatus,
'1.3.6.1.2.1.77.1.2.1.1': IF_INVERTED_STACK_MIB.ifInvStackGroup,
}
