#!/usr/bin/python -OOuS
# vim:ts=4:sw=4:softtabstop=0:smarttab

# All of the servers configuration, unix socket name, log file, and config
# file name are all determined by the name given as first non-option
# argument to this server.

# Set This python's instance to use UTF-8 as default. Note the use of the
# S flag above.

import sys
sys.setdefaultencoding("utf-8")
import site

from pycopia.WWW import fcgiserver

sys.exit(fcgiserver.run_server(sys.argv))

