#!/usr/bin/python

# This file generated by a program. do not edit.


import pycopia.XML.POM

attribName_1939937075622105121 = pycopia.XML.POM.XMLAttribute(u'name', 7, 12, None)


attribOnenterforward_1503730750383932004 = pycopia.XML.POM.XMLAttribute(u'onenterforward', 1, 12, None)


attribOnenterbackward_759618264702194041 = pycopia.XML.POM.XMLAttribute(u'onenterbackward', 1, 12, None)


attribMode_63769733202783204 = pycopia.XML.POM.XMLAttribute(u'mode', pycopia.XML.POM.Enumeration((u'wrap', u'nowrap')), 12, None)


attribLabel_507096964801122921 = pycopia.XML.POM.XMLAttribute(u'label', 1, 12, None)


attribNewcontext_3674167346276038756 = pycopia.XML.POM.XMLAttribute(u'newcontext', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')


attribPath_1403968622733128761 = pycopia.XML.POM.XMLAttribute(u'path', 1, 12, None)


attribVspace_995461752639063616 = pycopia.XML.POM.XMLAttribute(u'vspace', 1, 13, u'0')


attribClass_1166814720137472289 = pycopia.XML.POM.XMLAttribute(u'class', 1, 12, None)


attribSrc_3756099719576568676 = pycopia.XML.POM.XMLAttribute(u'src', 1, 11, None)


attribTabindex_1837810231620008409 = pycopia.XML.POM.XMLAttribute(u'tabindex', 7, 12, None)


attribHspace_1582921740062583684 = pycopia.XML.POM.XMLAttribute(u'hspace', 1, 13, u'0')


attribOnpick_1265868632723692176 = pycopia.XML.POM.XMLAttribute(u'onpick', 1, 12, None)


attribHttp_equiv_177552290082550681 = pycopia.XML.POM.XMLAttribute(u'http-equiv', 1, 12, None)


attribMethod_3652949412068207364 = pycopia.XML.POM.XMLAttribute(u'method', pycopia.XML.POM.Enumeration((u'post', u'get')), 13, u'get')


attribSize_2029701052474444441 = pycopia.XML.POM.XMLAttribute(u'size', 7, 12, None)


attribContent_542647257124694401 = pycopia.XML.POM.XMLAttribute(u'content', 1, 11, None)


attribXml_lang_1645670971257252241 = pycopia.XML.POM.XMLAttribute(u'xml:lang', 7, 12, None)


attribOptional_4060772272290282025 = pycopia.XML.POM.XMLAttribute(u'optional', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')


attribName_3839651748354608356 = pycopia.XML.POM.XMLAttribute(u'name', 1, 11, None)


attribColumns_385006860967402521 = pycopia.XML.POM.XMLAttribute(u'columns', 7, 11, None)


attribAccesskey_1489765571156059024 = pycopia.XML.POM.XMLAttribute(u'accesskey', 1, 12, None)


attribValue_94788037157002281 = pycopia.XML.POM.XMLAttribute(u'value', 1, 11, None)


attribIname_1981414652303599969 = pycopia.XML.POM.XMLAttribute(u'iname', 7, 12, None)


attribAlign_2555540542160179344 = pycopia.XML.POM.XMLAttribute(u'align', 1, 12, None)


attribType_3748092840448665856 = pycopia.XML.POM.XMLAttribute(u'type', pycopia.XML.POM.Enumeration((u'text', u'password')), 13, u'text')


attribAlt_3627988262564192641 = pycopia.XML.POM.XMLAttribute(u'alt', 1, 11, None)


attribValue_227024667205755136 = pycopia.XML.POM.XMLAttribute(u'value', 1, 12, None)


attribXml_space_2343687332552426884 = pycopia.XML.POM.XMLAttribute(u'xml:space', 1, 14, u'preserve')


attribHref_1415841210624387600 = pycopia.XML.POM.XMLAttribute(u'href', 1, 11, None)


attribForua_838160403938154049 = pycopia.XML.POM.XMLAttribute(u'forua', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')


attribDomain_2892948211515610000 = pycopia.XML.POM.XMLAttribute(u'domain', 1, 12, None)


attribScheme_1732839810197850225 = pycopia.XML.POM.XMLAttribute(u'scheme', 1, 12, None)


attribIvalue_143615738486755584 = pycopia.XML.POM.XMLAttribute(u'ivalue', 1, 12, None)


attribFormat_3672266847052825849 = pycopia.XML.POM.XMLAttribute(u'format', 1, 12, None)


attribTitle_1178737426446382009 = pycopia.XML.POM.XMLAttribute(u'title', 1, 12, None)


attribHeight_3964235387625190441 = pycopia.XML.POM.XMLAttribute(u'height', 1, 12, None)


attribMaxlength_4497231531995308681 = pycopia.XML.POM.XMLAttribute(u'maxlength', 7, 12, None)


attribSendreferer_3133377546496661025 = pycopia.XML.POM.XMLAttribute(u'sendreferer', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')


attribMultiple_16771446342335161 = pycopia.XML.POM.XMLAttribute(u'multiple', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')


attribId_4002951160133423716 = pycopia.XML.POM.XMLAttribute(u'id', 2, 12, None)


attribName_1485147577566348721 = pycopia.XML.POM.XMLAttribute(u'name', 1, 12, None)


attribEnctype_436576891689519025 = pycopia.XML.POM.XMLAttribute(u'enctype', 1, 13, u'application/x-www-form-urlencoded')


attribAlign_1715347099837610404 = pycopia.XML.POM.XMLAttribute(u'align', pycopia.XML.POM.Enumeration((u'top', u'middle', u'bottom')), 13, u'bottom')


attribLocalsrc_2505315932945154289 = pycopia.XML.POM.XMLAttribute(u'localsrc', 1, 12, None)


attribAccept_charset_349609442685618025 = pycopia.XML.POM.XMLAttribute(u'accept-charset', 1, 12, None)


attribAlign_4037419012459682529 = pycopia.XML.POM.XMLAttribute(u'align', pycopia.XML.POM.Enumeration((u'left', u'right', u'center')), 13, u'left')


attribOrdered_4108862243898239689 = pycopia.XML.POM.XMLAttribute(u'ordered', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'true')


attribWidth_936277652245334569 = pycopia.XML.POM.XMLAttribute(u'width', 1, 12, None)


attribOntimer_3666765203763203025 = pycopia.XML.POM.XMLAttribute(u'ontimer', 1, 12, None)


attribName_3478465917411609744 = pycopia.XML.POM.XMLAttribute(u'name', 7, 11, None)


attribType_1977399331530900489 = pycopia.XML.POM.XMLAttribute(u'type', 1, 11, None)


attribEmptyok_4505788268119429369 = pycopia.XML.POM.XMLAttribute(u'emptyok', pycopia.XML.POM.Enumeration((u'true', u'false')), 13, u'false')




# 
# Wireless Markup Language (WML) Document Type Definition.
# WML is an XML language. Typical usage:
#    <?xml version="1.0"?>
#    <!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.2//EN"
#    "http://www.wapforum.org/DTD/wml12.dtd">
#    <wml>
#    ...
#    </wml>
# 
#    Terms and conditions of use are available from the Wireless  Application Protocol Forum
#    Ltd. web site at http://www.wapforum.org/docs/copyright.htm.
# 
# 


#  [0-9]+ for pixels or [0-9]+"%" for
#                                         
# percentage length 


#  attribute value possibly containing
#                                          variable references 


#  URI, URL or URN designating a hypertext
#                                          node. May contain variable references 


#  a number, with format [0-9]+ 


#  media type. May contain variable
#                                          references 


#  flow covers "card-level" elements, such as text and images 


#  Task types 


#  Navigation and event elements 


# ================ Decks and Cards ================


class Wml(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'wml'



_Root = Wml



#  card intrinsic events 


#  card field types 


class Card(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'ordered': attribOrdered_4108862243898239689, 
         u'onenterbackward': attribOnenterbackward_759618264702194041, 
         u'title': attribTitle_1178737426446382009, 
         u'class': attribClass_1166814720137472289, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'ontimer': attribOntimer_3666765203763203025, 
         u'newcontext': attribNewcontext_3674167346276038756, 
         u'onenterforward': attribOnenterforward_1503730750383932004, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'ordered': attribOrdered_4108862243898239689, 
         'onenterbackward': attribOnenterbackward_759618264702194041, 
         'title': attribTitle_1178737426446382009, 
         'class_': attribClass_1166814720137472289, 
         'ontimer': attribOntimer_3666765203763203025, 
         'newcontext': attribNewcontext_3674167346276038756, 
         'onenterforward': attribOnenterforward_1503730750383932004, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'card'


# ================ Event Bindings ================


class Do(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'name': attribName_1939937075622105121, 
         u'type': attribType_1977399331530900489, 
         u'class': attribClass_1166814720137472289, 
         u'label': attribLabel_507096964801122921, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'optional': attribOptional_4060772272290282025, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'name': attribName_1939937075622105121, 
         'type': attribType_1977399331530900489, 
         'label': attribLabel_507096964801122921, 
         'class_': attribClass_1166814720137472289, 
         'optional': attribOptional_4060772272290282025, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'do'


class Onevent(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'type': attribType_1977399331530900489, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'type': attribType_1977399331530900489, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'onevent'


# ================ Deck-level declarations ================


class Head(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'head'


class Template(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         u'onenterforward': attribOnenterforward_1503730750383932004, 
         u'ontimer': attribOntimer_3666765203763203025, 
         u'onenterbackward': attribOnenterbackward_759618264702194041, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'id': attribId_4002951160133423716, 
         'class_': attribClass_1166814720137472289, 
         'onenterforward': attribOnenterforward_1503730750383932004, 
         'ontimer': attribOntimer_3666765203763203025, 
         'onenterbackward': attribOnenterbackward_759618264702194041, 
         }
	_name = u'template'


class Access(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'path': attribPath_1403968622733128761, 
         u'domain': attribDomain_2892948211515610000, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'path': attribPath_1403968622733128761, 
         'domain': attribDomain_2892948211515610000, 
         'id': attribId_4002951160133423716, 
         'class_': attribClass_1166814720137472289, 
         }
	_name = u'access'


class Meta(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'name': attribName_1485147577566348721, 
         u'forua': attribForua_838160403938154049, 
         u'class': attribClass_1166814720137472289, 
         u'content': attribContent_542647257124694401, 
         u'http-equiv': attribHttp_equiv_177552290082550681, 
         u'scheme': attribScheme_1732839810197850225, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'http_equiv': attribHttp_equiv_177552290082550681, 
         'forua': attribForua_838160403938154049, 
         'content': attribContent_542647257124694401, 
         'class_': attribClass_1166814720137472289, 
         'scheme': attribScheme_1732839810197850225, 
         'id': attribId_4002951160133423716, 
         'name': attribName_1485147577566348721, 
         }
	_name = u'meta'


# ================ Tasks ================


class Go(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'method': attribMethod_3652949412068207364, 
         u'accept-charset': attribAccept_charset_349609442685618025, 
         u'href': attribHref_1415841210624387600, 
         u'sendreferer': attribSendreferer_3133377546496661025, 
         u'id': attribId_4002951160133423716, 
         u'enctype': attribEnctype_436576891689519025, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'accept_charset': attribAccept_charset_349609442685618025, 
         'method': attribMethod_3652949412068207364, 
         'class_': attribClass_1166814720137472289, 
         'href': attribHref_1415841210624387600, 
         'sendreferer': attribSendreferer_3133377546496661025, 
         'id': attribId_4002951160133423716, 
         'enctype': attribEnctype_436576891689519025, 
         }
	_name = u'go'


class Prev(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'prev'


class Refresh(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'refresh'


class Noop(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'noop'


# ================ postfield ================


class Postfield(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'name': attribName_3839651748354608356, 
         u'value': attribValue_94788037157002281, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'name': attribName_3839651748354608356, 
         'value': attribValue_94788037157002281, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'postfield'


# ================ variables ================


class Setvar(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'name': attribName_3839651748354608356, 
         u'value': attribValue_94788037157002281, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'name': attribName_3839651748354608356, 
         'value': attribValue_94788037157002281, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'setvar'


# ================ Card Fields ================


class Select(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'multiple': attribMultiple_16771446342335161, 
         u'iname': attribIname_1981414652303599969, 
         u'title': attribTitle_1178737426446382009, 
         u'ivalue': attribIvalue_143615738486755584, 
         u'class': attribClass_1166814720137472289, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'value': attribValue_227024667205755136, 
         u'tabindex': attribTabindex_1837810231620008409, 
         u'id': attribId_4002951160133423716, 
         u'name': attribName_1939937075622105121, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'multiple': attribMultiple_16771446342335161, 
         'iname': attribIname_1981414652303599969, 
         'title': attribTitle_1178737426446382009, 
         'ivalue': attribIvalue_143615738486755584, 
         'class_': attribClass_1166814720137472289, 
         'value': attribValue_227024667205755136, 
         'tabindex': attribTabindex_1837810231620008409, 
         'id': attribId_4002951160133423716, 
         'name': attribName_1939937075622105121, 
         }
	_name = u'select'


class Optgroup(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'title': attribTitle_1178737426446382009, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         'title': attribTitle_1178737426446382009, 
         }
	_name = u'optgroup'


class Option(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'onpick': attribOnpick_1265868632723692176, 
         u'title': attribTitle_1178737426446382009, 
         u'value': attribValue_227024667205755136, 
         u'id': attribId_4002951160133423716, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'onpick': attribOnpick_1265868632723692176, 
         'title': attribTitle_1178737426446382009, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'value': attribValue_227024667205755136, 
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'option'


class Input(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'name': attribName_3478465917411609744, 
         u'format': attribFormat_3672266847052825849, 
         u'accesskey': attribAccesskey_1489765571156059024, 
         u'title': attribTitle_1178737426446382009, 
         u'value': attribValue_227024667205755136, 
         u'class': attribClass_1166814720137472289, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'emptyok': attribEmptyok_4505788268119429369, 
         u'maxlength': attribMaxlength_4497231531995308681, 
         u'tabindex': attribTabindex_1837810231620008409, 
         u'type': attribType_3748092840448665856, 
         u'id': attribId_4002951160133423716, 
         u'size': attribSize_2029701052474444441, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'name': attribName_3478465917411609744, 
         'format': attribFormat_3672266847052825849, 
         'accesskey': attribAccesskey_1489765571156059024, 
         'title': attribTitle_1178737426446382009, 
         'value': attribValue_227024667205755136, 
         'class_': attribClass_1166814720137472289, 
         'emptyok': attribEmptyok_4505788268119429369, 
         'maxlength': attribMaxlength_4497231531995308681, 
         'tabindex': attribTabindex_1837810231620008409, 
         'type': attribType_3748092840448665856, 
         'id': attribId_4002951160133423716, 
         'size': attribSize_2029701052474444441, 
         }
	_name = u'input'


class Fieldset(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'title': attribTitle_1178737426446382009, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         'title': attribTitle_1178737426446382009, 
         }
	_name = u'fieldset'


class Timer(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'name': attribName_1939937075622105121, 
         u'value': attribValue_94788037157002281, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'name': attribName_1939937075622105121, 
         'value': attribValue_94788037157002281, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'timer'


# ================ Images ================


class Img(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'src': attribSrc_3756099719576568676, 
         u'localsrc': attribLocalsrc_2505315932945154289, 
         u'class': attribClass_1166814720137472289, 
         u'align': attribAlign_1715347099837610404, 
         u'height': attribHeight_3964235387625190441, 
         u'width': attribWidth_936277652245334569, 
         u'vspace': attribVspace_995461752639063616, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'alt': attribAlt_3627988262564192641, 
         u'hspace': attribHspace_1582921740062583684, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'src': attribSrc_3756099719576568676, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'localsrc': attribLocalsrc_2505315932945154289, 
         'class_': attribClass_1166814720137472289, 
         'align': attribAlign_1715347099837610404, 
         'height': attribHeight_3964235387625190441, 
         'width': attribWidth_936277652245334569, 
         'vspace': attribVspace_995461752639063616, 
         'alt': attribAlt_3627988262564192641, 
         'hspace': attribHspace_1582921740062583684, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'img'


# ================ Anchor ================


class Anchor(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'accesskey': attribAccesskey_1489765571156059024, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'title': attribTitle_1178737426446382009, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'id': attribId_4002951160133423716, 
         'class_': attribClass_1166814720137472289, 
         'accesskey': attribAccesskey_1489765571156059024, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'title': attribTitle_1178737426446382009, 
         }
	_name = u'anchor'


class A(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'title': attribTitle_1178737426446382009, 
         u'accesskey': attribAccesskey_1489765571156059024, 
         u'class': attribClass_1166814720137472289, 
         u'href': attribHref_1415841210624387600, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'title': attribTitle_1178737426446382009, 
         'accesskey': attribAccesskey_1489765571156059024, 
         'class_': attribClass_1166814720137472289, 
         'href': attribHref_1415841210624387600, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'a'


# ================ Tables ================


class Table(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'title': attribTitle_1178737426446382009, 
         u'align': attribAlign_2555540542160179344, 
         u'id': attribId_4002951160133423716, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'class': attribClass_1166814720137472289, 
         u'columns': attribColumns_385006860967402521, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'xml_lang': attribXml_lang_1645670971257252241, 
         'title': attribTitle_1178737426446382009, 
         'align': attribAlign_2555540542160179344, 
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         'columns': attribColumns_385006860967402521, 
         }
	_name = u'table'


class Tr(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'tr'


class Td(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'td'


# ================ Text layout and line breaks ================


class Em(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'em'


class Strong(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'strong'


class B(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'b'


class I(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'i'


class U(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'u'


class Big(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'big'


class Small(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'small'


class P(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'class': attribClass_1166814720137472289, 
         u'align': attribAlign_4037419012459682529, 
         u'xml:lang': attribXml_lang_1645670971257252241, 
         u'mode': attribMode_63769733202783204, 
         u'id': attribId_4002951160133423716, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'align': attribAlign_4037419012459682529, 
         'xml_lang': attribXml_lang_1645670971257252241, 
         'mode': attribMode_63769733202783204, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'p'


class Br(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel(None)
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'br'


class Pre(pycopia.XML.POM.ElementNode):
	ATTRIBUTES = {
         u'xml:space': attribXml_space_2343687332552426884, 
         u'id': attribId_4002951160133423716, 
         u'class': attribClass_1166814720137472289, 
         }
	CONTENTMODEL = pycopia.XML.POM.ContentModel((True,))
	KWATTRIBUTES = {
         'class_': attribClass_1166814720137472289, 
         'xml_space': attribXml_space_2343687332552426884, 
         'id': attribId_4002951160133423716, 
         }
	_name = u'pre'


#  quotation mark 


#  ampersand 


#  apostrophe 


#  less than 


#  greater than 


#  non-breaking space 


#  soft hyphen (discretionary hyphen) 


GENERAL_ENTITIES = {'gt': u'>', 'quot': u'"', 'shy': u'\xad', 'lt': u'&#60;', 'nbsp': u'\xa0', 'amp': u'&#38;', 'apos': u"'"}

# Cache for dynamic classes for this dtd.


_CLASSCACHE = {}


